---
title: "DataFest Qing"
author: "Qing Shi"
date: "5/9/2020"
output: html_document
---

```{r message = FALSE}
library(dplyr)
world <- read.csv("./src/Global_Mobility_Report.csv")
us <- world %>% filter(country_region == "United States")
```

#### AQI for NY
```{r message = FALSE}
library(dplyr)
Weekdays <- rep(c("Fri", "Sat", "Sun", "Mon", "Tue", "Wed", "Thu"), 5)

ny <- read.csv("./src/NY-PM2.5.csv")
ny <- ny %>% arrange(Date) # actually contains AQI, if want to add/change later

# select only date, county, AQI, state (all ny)
simple_ny <- ny %>%  select(Date, COUNTY, DAILY_AQI_VALUE, STATE) 

# median AQI value by date
median_ny <- simple_ny %>% group_by(Date) %>% summarize(AQI.Median = median(DAILY_AQI_VALUE))

# dates and values that would be considered to find baseline
baseline_ny <- median_ny[3:37,]
baseline_ny <- cbind(baseline_ny, Weekdays)

# seven median values for ny
baseline_ny_median <- baseline_ny %>% group_by(Weekdays) %>% summarize(median = median(AQI.Median))

baseline_ny_median <- baseline_ny_median[c(3,4,2,6,7,5,1),]

# data of ny from 3.12 to 5.1
ny_after <- median_ny[81:122,]
baseline_ny_median <- rep(baseline_ny_median$median, 6)
weekdays <- rep(c("Sat", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri"), 6)
ny_after <- cbind(ny_after, baseline_ny_median)

# percent change from baseline
ny_change_from_baseline <- ny_after %>% mutate(Change_from_Baseline = (AQI.Median - baseline_ny_median) / baseline_ny_median * 100)
plot(ny_change_from_baseline$Change_from_Baseline, col = "blue")
```

#### Mobility for NY
```{r}
# now mobility change
ny_mobility <- us %>% filter(sub_region_1 == "New York")
ny_mobility <- ny_mobility %>% select(sub_region_1, date, transit_stations_percent_change_from_baseline)
ny_mobility <- ny_mobility %>% group_by(date) %>% summarize(transit_stations_percent_change_from_baseline = median(transit_stations_percent_change_from_baseline, na.rm = TRUE))
# data from 3.12 to 5.1
ny_mobility <- ny_mobility[36:77,]

plot(1:42, change_from_baseline$Change_from_Baseline, col = "blue", type = "l", ylim = c(-100, 50))
points(ny_mobility$transit_stations_percent_change_from_baseline, col = "red", type = "l")
abline(h = 0, col = "gray", lty = 2)
legend("topleft", legend = c("Mobility Change", "AQI change"), col = c("blue", "red"), lty = 1, cex=0.8)
```

#### Plot and save the graph (NY)
```{r}
# 1. Open pdf file
pdf("NY-AQI-change-from-baseilne.pdf")
# 2. Create the plot
plot(1:42, change_from_baseline$Change_from_Baseline, 
     col = "blue", type = "l", ylim = c(-100, 50), 
     xlab = "Days", ylab = "Change from Baseline (%)",
     main = "NY Mobility Change and AQI Change from Baseline")
points(ny_mobility$transit_stations_percent_change_from_baseline, col = "red", type = "l")
abline(h = 0, col = "gray", lty = 2)
legend("topleft", legend = c("Mobility Change", "AQI change"), col = c("blue", "red"), lty = 1, cex=0.8)
# 3. Close the file
dev.off()
```
#### Save result to .csv file
```{r}
write.csv(ny_change_from_baseline, "NY_daily_air_quality_change_from_baseline.csv")
```
#### AQI for CA
```{r}
ca <- read.csv("./src/CA-PM2.5.csv")
Weekdays <- rep(c("Fri", "Sat", "Sun", "Mon", "Tue", "Wed", "Thu"), 5)

ca <- ca %>% arrange(Date) # actually contains AQI, if want to add/change later

# select only date, county, AQI, state (all ca)
simple_ca <- ca %>%  select(Date, COUNTY, DAILY_AQI_VALUE, STATE) 

# median AQI value by date
median_ca <- simple_ca %>% group_by(Date) %>% summarize(AQI.Median = median(DAILY_AQI_VALUE))

# dates and values that would be considered to find baseline
baseline_ca <- median_ca[3:37,]
baseline_ca <- cbind(baseline_ca, Weekdays)

# seven median values for ca
baseline_ca_median <- baseline_ca %>% group_by(Weekdays) %>% summarize(median = median(AQI.Median))

baseline_ca_median <- baseline_ca_median[c(3,4,2,6,7,5,1),]

# data of ca from 3.12 to 5.1
ca_after <- median_ca[81:122,]
baseline_ca_median <- rep(baseline_ca_median$median, 6)
weekdays <- rep(c("Sat", "Sun", "Mon", "Tue", "Wed", "Thu", "Fri"), 6)
ca_after <- cbind(ca_after, baseline_ca_median)

# percent change from baseline
ca_change_from_baseline <- ca_after %>% mutate(Change_from_Baseline = (AQI.Median - baseline_ca_median) / baseline_ca_median * 100)
plot(ca_change_from_baseline$Change_from_Baseline, col = "blue")
```

#### Mobility for CA
```{r}
# now mobility change
ca_mobility <- us %>% filter(sub_region_1 == "California")
ca_mobility <- ca_mobility %>% select(sub_region_1, date, transit_stations_percent_change_from_baseline)
ca_mobility <- ca_mobility %>% group_by(date) %>% summarize(transit_stations_percent_change_from_baseline = median(transit_stations_percent_change_from_baseline, na.rm = TRUE))
# data from 3.12 to 5.1
ca_mobility <- ca_mobility[36:77,]

plot(1:42, change_from_baseline$Change_from_Baseline, col = "blue", type = "l", ylim = c(-100, 50))
points(ca_mobility$transit_stations_percent_change_from_baseline, col = "red", type = "l")
abline(h = 0, col = "gray", lty = 2)
legend("topleft", legend = c("Mobility Change", "AQI Change"), col = c("blue", "red"), lty = 1, cex=0.8)

plot(change_from_baseline$Change_from_Baseline ~ ca_mobility$transit_stations_percent_change_from_baseline)
abline(lm(change_from_baseline$Change_from_Baseline ~ ca_mobility$transit_stations_percent_change_from_baseline))
summary(lm(change_from_baseline$Change_from_Baseline ~ ca_mobility$transit_stations_percent_change_from_baseline))
```

#### Plot and save the graph (CA)
```{r}
# 1. Open pdf file
pdf("CA-AQI-change-from-baseilne.pdf")
# 2. Create the plot
plot(1:42, ca_change_from_baseline$Change_from_Baseline, 
     col = "blue", type = "l", ylim = c(-100, 50), 
     xlab = "Days", ylab = "Change from Baseline (%)",
     main = "CA Mobility Change and AQI Change from Baseline")
points(ca_mobility$transit_stations_percent_change_from_baseline, col = "red", type = "l")
abline(h = 0, col = "gray", lty = 2)
legend("topleft", legend = c("Mobility Change", "AQI Change"), col = c("blue", "red"), lty = 1, cex=0.8)
# 3. Close the file
dev.off()
```

#### Save result to .csv file
```{r}
write.csv(ca_change_from_baseline, "CA_daily_air_quality_change_from_baseline.csv")
```